GET http://localhost:3000/logins HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYjdkYjQwOS0xYjQ4LTQ1MDYtOGU5Ny1jY2RlNDBmYjc3OTAiLCJlbWFpbCI6Imx1aXpoZW5yaXF1ZWRvbWluaWNvQGdtYWlsLmNvbSIsImlhdCI6MTcyOTg1MjAzMCwiZXhwIjoxNzI5ODUzODMwfQ.74V8pZQ756piDiFcMPzhdwua1V6n1uVYOOuqbjfeRws
Content-Type: application/json