GET http://localhost:3000/profiles HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYjdkYjQwOS0xYjQ4LTQ1MDYtOGU5Ny1jY2RlNDBmYjc3OTAiLCJlbWFpbCI6Imx1aXpoZW5yaXF1ZWRvbWluaWNvQGdtYWlsLmNvbSIsImlhdCI6MTcyOTg0Mzc2OCwiZXhwIjoxNzI5ODQ1NTY4fQ.s6wceaKHM9WccEDrHFNgNK5c4r_KlS6uHnEsQsuN9vM
Content-Type: application/json
