GET http://localhost:3000/home HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNjc3Nzc1Zi1hNTVhLTQ1MDMtYmZiMi0wN2I5ZTRmM2ZlYWMiLCJlbWFpbCI6Imx1aXpoZW5yaXF1ZWRvbWluaWNvQGdtYWlsLmNvbSIsImlhdCI6MTcyOTc1Mjc4MiwiZXhwIjoxNzI5NzU0NTgyfQ.h0Q0-3yMhsKP8hdtnnRZ09z_d_QAh4zmA-giesguR84