GET http://localhost:3000/home HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NGMyMzQ5Mi1lYjcwLTQzMjgtODgzNS1mMWE5ZGFiNjk5YTIiLCJlbWFpbCI6Imx1aXpoZW5yaXF1ZWRvbWluaWNvQGdtYWlsLmNvbSIsImlhdCI6MTcyOTcyNDc2OSwiZXhwIjoxNzI5NzI2NTY5fQ.DZMdqj6hgHzttnAbdEvGUotgUZqsSJ3ZZAk14iGTiEA