PUT http://localhost:3000/profiles HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMWNkZjBhYS1hMDFmLTQ1ZjgtODc0OC1mYTI4MzEzNjQ3MTMiLCJlbWFpbCI6Imx1aXpoZW5yaXF1ZWRvbWluaWNvQGdtYWlsLmNvbSIsImlhdCI6MTcyOTk2ODY5OSwiZXhwIjoxNzI5OTcwNDk5fQ.qjQ-19FB9VMMuXg5uRGm4jeZiuDDj1zi6ogQJs_uVzc
Content-Type: application/json

{
    "name": "Luiz Henrique Dominico",
    "birth": "1999-09-20"
}